# Generated by Django 5.0.1 on 2024-01-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='paciente',
            name='aseguradora',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='calle',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudad',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='comentario',
            field=models.CharField(default='n/a', max_length=400),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cp',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='documento_identidad',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_seguro',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otros_datos',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pais',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='puerta',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_adicional',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='LPD',
            field=models.URLField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
